 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
 package frc.robot.input;
 public class Button extends java.awt.Component implements javax.accessibility.Accessible {
   
   java.lang.String label;
   
   java.lang.String actionCommand;
   
   transient java.awt.event.ActionListener actionListener;
   
   private static final java.lang.String base = "button";
   
   private static int nameCounter;
   
   private static final long serialVersionUID = -8774683716313001058L;
   
   private int buttonSerializedDataVersion;
   
   private static native void initIDs();
   
   public Button() throws java.awt.HeadlessException {
   }
   
   public Button(java.lang.String label) throws java.awt.HeadlessException {
   }
   
   java.lang.String constructComponentName() {
     return null;
   }
   
   public void addNotify() {
   }
   
   public java.lang.String getLabel() {
     return null;
   }
   
   public void setLabel(java.lang.String label) {
   }
   
   public void setActionCommand(java.lang.String command) {
   }
   
   public java.lang.String getActionCommand() {
     return null;
   }
   
   public synchronized void addActionListener(java.awt.event.ActionListener l) {
   }
   
   public synchronized void removeActionListener(java.awt.event.ActionListener l) {
   }
   
   public synchronized java.awt.event.ActionListener[] getActionListeners() {
     return null;
   }
   
   public <T extends java.util.EventListener> T[] getListeners(java.lang.Class<T> listenerType) {
     return null;
   }
   
   boolean eventEnabled(java.awt.AWTEvent e) {
     return false;
   }
   
   protected void processEvent(java.awt.AWTEvent e) {
   }
   
   protected void processActionEvent(java.awt.event.ActionEvent e) {
   }
   
   protected java.lang.String paramString() {
     return null;
   }
   
   private void writeObject(java.io.ObjectOutputStream s) throws java.io.IOException {
   }
   
   private void readObject(java.io.ObjectInputStream s) throws java.lang.ClassNotFoundException, java.io.IOException, java.awt.HeadlessException {
   }
   
   public javax.accessibility.AccessibleContext getAccessibleContext() {
     return null;
   }
   
   static {} {
   }
 }